disable-publish = true
no-dev-version = true
pre-release-replacements = [
  {file="bindings/sai_wasm/Cargo.toml", search="\nversion = \"[a-z0-9\\.-]+\"", replace="\nversion = \"{{version}}\"", exactly=1},
  {file="bindings/sai_python/Cargo.toml", search="\nversion = \"[a-z0-9\\.-]+\"", replace="\nversion = \"{{version}}\"", exactly=1}
]
